### PR TITLE
test2

### PR DESCRIPTION
**Pull request by daveba**

### CODE REVIEW

**Comment by daveba** [comment]
#sign-off

**Comment by herohua** [comment]
# Open Publishing Service
Your pull request has been validated.

### Validation status: :x:Errors

Here is the list of files that get changed in this pull request:


File | Status | Preview URL | Details
---- | --------| --------| ------------
[daveba-prmerger-test/testing.md](https://github.com/herohua/markdown-test/blob/prmerger-test2/daveba-prmerger-test/testing.md) | :white_check_mark:Succeeded | | [Details](#user-content-daveba-prmerger-test/testing.md)

Here are detailed warnings/errors in each file:


For more details, please refer to the [publish report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2016%5C11%5C4%5C55506563-8dd2-b513-6276-829687a360b3%5CPullRequest%5C201611042325076108-9%5Cworkflow_report.html).

**Comment by herohua** [comment]
# Open Publishing Service
Your pull request has been validated and published.

### Validation status: :white_check_mark:Passed

Here is the list of files that get changed in this pull request:


File | Status | Preview URL | Details
---- | --------| --------| ------------

For more details, please refer to the [publish report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2016%5C11%5C4%5C55506563-8dd2-b513-6276-829687a360b3%5CPullRequest%5C201611042326065247-9%5Cworkflow_report.html).

**Comment by herohua** [comment]
# Open Publishing Service
Your pull request has been validated and published.

### Validation status: :white_check_mark:Passed

Here is the list of files that get changed in this pull request:


File | Status | Preview URL | Details
---- | --------| --------| ------------

For more details, please refer to the [publish report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2016%5C11%5C4%5C55506563-8dd2-b513-6276-829687a360b3%5CPullRequest%5C201611042326430320-9%5Cworkflow_report.html).

**Comment by herohua** [comment]
# Open Publishing Service
Your pull request has been validated and published.

### Validation status: :white_check_mark:Passed

Here is the list of files that get changed in this pull request:


File | Status | Preview URL | Details
---- | --------| --------| ------------

For more details, please refer to the [publish report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2016%5C11%5C4%5C55506563-8dd2-b513-6276-829687a360b3%5CPullRequest%5C201611042329280851-9%5Cworkflow_report.html).

**Pull request merged**
